# Generated by Django 4.1 on 2022-08-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('deli', 'Deli'), ('restaurant', 'Restaurant'), ('apparel', 'Apparel'), ('art supplies', 'Art Supplies'), ('bookshop', 'Bookshops'), ('drug store', 'Drug Store'), ('grocery store', 'Grocery Store'), ('plant nursery', 'Plant Nursery'), ('other', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.CharField(choices=[('east northeast', 'East and Northeast LA'), ('downtown', 'Downtown LA'), ('echopark westlake', 'Echo Park and Westlake'), ('hollywood', 'Hollywood'), ('harbor area', 'Harbor Area'), ('los feliz silverlake', 'Los Feliz and Silverlake'), ('south central', 'South Central'), ('sfv', 'San Fernando Valley'), ('west', 'West LA'), ('wilshire', 'Wilshire')], max_length=150),
        ),
    ]
