# Generated by Django 4.1 on 2022-08-27 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_post_category_alter_post_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'svg', 'heic'])]),
        ),
    ]
