# Generated by Django 4.1 on 2022-08-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('deli', 'Deli'), ('restaurant', 'Restaurant'), ('apparel', 'Apparel'), ('art supplies', 'Art Supplies'), ('beauty supplies', 'Beauty Supplies'), ('bookshop', 'Bookshops'), ('drug store', 'Drug Store'), ('grocery store', 'Grocery Store'), ('plant nursery', 'Plant Nursery'), ('children boutiques', 'Children Boutiques'), ('other', 'Other')], max_length=150),
        ),
    ]
