# Generated by Django 4.1 on 2022-08-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_post_address_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Deli', 'Deli'), ('Restaurant', 'Restaurant'), ('Apparel', 'Apparel'), ('Art Supplies', 'Art Supplies'), ('Beauty Supplies', 'Beauty Supplies'), ('Bookshop', 'Bookshop'), ('Drug Store', 'Drug Store'), ('Grocery Store', 'Grocery Store'), ('Plant Nursery', 'Plant Nursery'), ('Children Boutique', 'Children Boutique'), ('Other', 'Other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.CharField(choices=[('East and Northeast LA', 'East and Northeast LA'), ('Downtown LA', 'Downtown LA'), ('Echo Park and Westlake', 'Echo Park and Westlake'), ('Hollywood', 'Hollywood'), ('Harbor Area', 'Harbor Area'), ('Los Feliz and Silverlake', 'Los Feliz and Silverlake'), ('South Central', 'South Central'), ('San Fernando Valley', 'San Fernando Valley'), ('West LA', 'West LA'), ('Wilshire', 'Wilshire')], max_length=250),
        ),
    ]
