# Generated by Django 4.1.1 on 2023-01-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_post_category_alter_post_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
